spring.application.name=spring-sql-demo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fifapp?currentSchema=flyway_training
spring.datasource.username=fifapp_admin
spring.datasource.password=fifapp_admin
spring.datasource.driver-class-name=org.postgresql.Driver
# Target Schema
#spring.datasource.hikari.schema=flyway_training

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=flyway_training
spring.flyway.default-schema=flyway_training
spring.flyway.create-schemas=true
